version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:8-browser     
         
    steps:
      - checkout      
      - run: yarn ng build --prod
      - run: yarn test --single-run
  test:
    docker:
      - image: circleci/node         
    steps:
      - checkout
      - run: echo "this is the test job"

